### PR TITLE
check if hdf5 attribute exists before creating it

### LINKED ISSUE #109: HDF5 Filewriter is broken with MULTISET
there is a bug in the current version of the hdf5 filewriter that causes lima to break in MULTISET writing mode. 
The problem is that it tries to recreate the /default property when opening the file to append new data and that property already exists causing an exception.

### PR DESCRIPTION
**Pull request by weninc**
fix  #109

### CODE REVIEW

**Comment by weninc** [comment]
ping @laurent-claustre

**Comment by sdebionne** [comment]
LGTM, thanks!

**Comment by laurent-claustre** [comment]
Hi @weninc,
the merge is ongoing on our CI on gitlab.esrf.fr. When done, github.com will be updated and your PR too.
For which detectors are you using Lima on  MaxIV beamlines?

**Comment by weninc** [comment]
Great thank you. We are using Lima for quite a few detectors here at MAX IV including Andor3, Pilatus, Merlin and Xspress3

**Comment by laurent-claustre** [comment]
Our CI pipeline is broken under windows with due to a conda issue, once fix I will merge. Sorry for the delay.

**Comment by sdebionne** [comment]
@weninc Sorry it took so long to merge, we were affected by conda/conda#9578.

**Comment by weninc** [comment]
No Problem. Thanks a lot for getting it merged

**Pull request closed without merging**
